/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{

    /*2.1. Operador AND: la máscara que revela*/
    
    uint8_t value_1 = 0b10110101;     /*0xB5=181*/
    uint8_t mask_1 = 0b00001111;      /*0x0F=15*/
    uint8_t result_1 = value_1 & mask_1;  /*0b0000101=0x05=5*/
    /*la máscara que usaría para  extraer solo los
    4 bits superiores seria ob11110000*/

    /*2.2. Operador OR: la máscara que establece*/

    uint8_t value_2 = 0b10100000;     /*160*/
    uint8_t mask_2 = 0b00000101;      /*5*/
    uint8_t result_2 = value_2 | mask_2;  /*165*/


    /*si un bit ya es 1 y se le aplica OR con 1 ese bit queda en 1
    si un bit es 0 y se le aplica OR con 0 conserva el 0*/

    /*2.3. Operador NOT: el complemento*/

    uint8_t a = 0b00001111;     /*15*/
    uint8_t result1 = ~a;       /*ob11110000=240*/
    uint8_t b = 0b10100101;     /*165*/
    uint8_t result2 = ~b;       /*0b01011010=90*/
    
    uint8_t value_3 = 0b11111111;   /*255*/
    uint8_t mask_3  = 0b11;         /*3*/
    value_3 &= ~mask_3;              /*252*/



    while (1)
    {

    }
    return 0;
}
